// Generated by Supabase (generate_typescript_types) for the job-tracker
// project. Regenerate after schema changes rather than editing by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      applications: {
        Row: {
          applied_on: string
          company: string
          created_at: string
          description: string | null
          id: string
          location: string | null
          notes: string | null
          role: string
          source: string
          status: string
          status_changed_at: string | null
          updated_at: string
          url: string | null
          user_id: string
        }
        Insert: {
          applied_on?: string
          company: string
          created_at?: string
          description?: string | null
          id?: string
          location?: string | null
          notes?: string | null
          role: string
          source?: string
          status?: string
          status_changed_at?: string | null
          updated_at?: string
          url?: string | null
          user_id?: string
        }
        Update: {
          applied_on?: string
          company?: string
          created_at?: string
          description?: string | null
          id?: string
          location?: string | null
          notes?: string | null
          role?: string
          source?: string
          status?: string
          status_changed_at?: string | null
          updated_at?: string
          url?: string | null
          user_id?: string
        }
        Relationships: []
      }
      assessments: {
        Row: {
          application_id: string
          completed_at: string | null
          created_at: string
          details: string | null
          due_at: string | null
          duration_min: number | null
          id: string
          important: boolean
          interviewer: string | null
          kind: string
          link: string | null
          notes: string | null
          status: string
          title: string
          user_id: string
        }
        Insert: {
          application_id: string
          completed_at?: string | null
          created_at?: string
          details?: string | null
          due_at?: string | null
          duration_min?: number | null
          id?: string
          important?: boolean
          interviewer?: string | null
          kind?: string
          link?: string | null
          notes?: string | null
          status?: string
          title: string
          user_id?: string
        }
        Update: {
          application_id?: string
          completed_at?: string | null
          created_at?: string
          details?: string | null
          due_at?: string | null
          duration_min?: number | null
          id?: string
          important?: boolean
          interviewer?: string | null
          kind?: string
          link?: string | null
          notes?: string | null
          status?: string
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "assessments_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      status_changes: {
        Row: {
          application_id: string
          changed_at: string | null
          id: string
          origin: string
          status: string
          user_id: string
        }
        Insert: {
          application_id: string
          changed_at?: string | null
          id?: string
          origin?: string
          status: string
          user_id: string
        }
        Update: {
          application_id?: string
          changed_at?: string | null
          id?: string
          origin?: string
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "status_changes_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      import_rows: { Args: { payload: Json }; Returns: Json }
      status_origin: { Args: never; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never
