// Generated by Supabase (generate_typescript_types) for the job-tracker
// project. Regenerate after schema changes rather than editing by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      applications: {
        Row: {
          applied_on: string
          company: string
          created_at: string
          description: string | null
          id: string
          location: string | null
          notes: string | null
          role: string
          source: string
          status: string
          status_changed_at: string | null
          updated_at: string
          url: string | null
          user_id: string
        }
        Insert: {
          applied_on?: string
          company: string
          created_at?: string
          description?: string | null
          id?: string
          location?: string | null
          notes?: string | null
          role: string
          source?: string
          status?: string
          status_changed_at?: string | null
          updated_at?: string
          url?: string | null
          user_id?: string
        }
        Update: {
          applied_on?: string
          company?: string
          created_at?: string
          description?: string | null
          id?: string
          location?: string | null
          notes?: string | null
          role?: string
          source?: string
          status?: string
          status_changed_at?: string | null
          updated_at?: string
          url?: string | null
          user_id?: string
        }
        Relationships: []
      }
      assessment_questions: {
        Row: {
          answer: string | null
          assessment_id: string
          created_at: string
          id: string
          question: string
          source: string
          user_id: string
        }
        Insert: {
          answer?: string | null
          assessment_id: string
          created_at?: string
          id?: string
          question: string
          source?: string
          user_id?: string
        }
        Update: {
          answer?: string | null
          assessment_id?: string
          created_at?: string
          id?: string
          question?: string
          source?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "assessment_questions_assessment_id_fkey"
            columns: ["assessment_id"]
            isOneToOne: false
            referencedRelation: "assessments"
            referencedColumns: ["id"]
          },
        ]
      }
      assessments: {
        Row: {
          application_id: string
          completed_at: string | null
          created_at: string
          details: string | null
          difficulty: number | null
          due_at: string | null
          duration_min: number | null
          id: string
          important: boolean
          interviewer: string | null
          kind: string
          link: string | null
          notes: string | null
          outcome: string | null
          prep_notes: string | null
          reflection: string | null
          score: string | null
          status: string
          title: string
          user_id: string
        }
        Insert: {
          application_id: string
          completed_at?: string | null
          created_at?: string
          details?: string | null
          difficulty?: number | null
          due_at?: string | null
          duration_min?: number | null
          id?: string
          important?: boolean
          interviewer?: string | null
          kind?: string
          link?: string | null
          notes?: string | null
          outcome?: string | null
          prep_notes?: string | null
          reflection?: string | null
          score?: string | null
          status?: string
          title: string
          user_id?: string
        }
        Update: {
          application_id?: string
          completed_at?: string | null
          created_at?: string
          details?: string | null
          difficulty?: number | null
          due_at?: string | null
          duration_min?: number | null
          id?: string
          important?: boolean
          interviewer?: string | null
          kind?: string
          link?: string | null
          notes?: string | null
          outcome?: string | null
          prep_notes?: string | null
          reflection?: string | null
          score?: string | null
          status?: string
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "assessments_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      message_templates: {
        Row: {
          body: string
          channel: string
          created_at: string
          id: string
          name: string
          updated_at: string
          user_id: string
        }
        Insert: {
          body: string
          channel: string
          created_at?: string
          id?: string
          name: string
          updated_at?: string
          user_id?: string
        }
        Update: {
          body?: string
          channel?: string
          created_at?: string
          id?: string
          name?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      moves: {
        Row: {
          application_id: string | null
          channel: string
          closed: boolean
          created_at: string
          follow_ups: number
          id: string
          last_touch_at: string
          link: string | null
          message: string | null
          minutes: number
          notes: string | null
          replied_at: string | null
          stage: string
          target: string
          template_key: string | null
          updated_at: string
          user_id: string
          waiting_on: string
        }
        Insert: {
          application_id?: string | null
          channel: string
          closed?: boolean
          created_at?: string
          follow_ups?: number
          id?: string
          last_touch_at?: string
          link?: string | null
          message?: string | null
          minutes?: number
          notes?: string | null
          replied_at?: string | null
          stage?: string
          target: string
          template_key?: string | null
          updated_at?: string
          user_id?: string
          waiting_on?: string
        }
        Update: {
          application_id?: string | null
          channel?: string
          closed?: boolean
          created_at?: string
          follow_ups?: number
          id?: string
          last_touch_at?: string
          link?: string | null
          message?: string | null
          minutes?: number
          notes?: string | null
          replied_at?: string | null
          stage?: string
          target?: string
          template_key?: string | null
          updated_at?: string
          user_id?: string
          waiting_on?: string
        }
        Relationships: [
          {
            foreignKeyName: "moves_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      status_changes: {
        Row: {
          application_id: string
          changed_at: string | null
          id: string
          origin: string
          status: string
          user_id: string
        }
        Insert: {
          application_id: string
          changed_at?: string | null
          id?: string
          origin?: string
          status: string
          user_id: string
        }
        Update: {
          application_id?: string
          changed_at?: string | null
          id?: string
          origin?: string
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "status_changes_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      time_log: {
        Row: {
          day: string
          seconds: number
          updated_at: string
          user_id: string
        }
        Insert: {
          day: string
          seconds?: number
          updated_at?: string
          user_id?: string
        }
        Update: {
          day?: string
          seconds?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_move_minutes: {
        Args: { p_id: string; p_minutes: number }
        Returns: number
      }
      add_time: { Args: { p_day: string; p_seconds: number }; Returns: number }
      import_rows: { Args: { payload: Json }; Returns: Json }
      set_time: { Args: { p_day: string; p_seconds: number }; Returns: number }
      status_origin: { Args: never; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never
